### ISSUE TITLE
StageException: Could not QC barcodes: return code -9

### ISSUE THREAD

**Issue by amirshams84** [10XGenomics/cellranger#102]
Hi 
I am receiving the following error and the QC script crashes
`[error] Pipestance failed. Error log at:
AAAGLTJM5/MAKE_FASTQS_CS/MAKE_FASTQS/MAKE_QC_SUMMARY/fork0/chnk05-u91b4ae111a/_errors

Log message:
Traceback (most recent call last):
  File "/usr/local/apps/cellranger/4.0.0/external/martian/adapters/python/martian_shell.py", line 587, in _main
    stage.main()
  File "/usr/local/apps/cellranger/4.0.0/external/martian/adapters/python/martian_shell.py", line 552, in main
    self._run(lambda: self._module.main(args, outs))
  File "/usr/local/apps/cellranger/4.0.0/external/martian/adapters/python/martian_shell.py", line 521, in _run
    cmd()
  File "/usr/local/apps/cellranger/4.0.0/external/martian/adapters/python/martian_shell.py", line 552, in <lambda>
    self._run(lambda: self._module.main(args, outs))
  File "/usr/local/apps/cellranger/4.0.0/mro/tenkit/stages/make_fastqs/make_qc_summary/__init__.py", line 302, in main
    martian.throw("Could not QC barcodes: return code %s" % e.returncode)
  File "/usr/local/apps/cellranger/4.0.0/external/martian/adapters/python/martian.py", line 259, in throw
    raise StageException(message)
StageException: Could not QC barcodes: return code -9`

**Comment by evolvedmicrobe** [comment]
Please contact support@10xgenomics.com for help with this issue, the `9` return code likely means that something sent a `SIGKILL` to the process and ended it prematurely.
