### ISSUE TITLE
cellranger-7.1.0: Fix cluster execution --jobmode=torque and --jobmode=pbspro

### ISSUE THREAD

**Issue by mmokrejs** [10XGenomics/cellranger#219]
Hi,
  in clustermode the *child* jobs are executed from under martians shell, which get executed on the execution node. Somewhere the environment is being reset so the python tools fail to import python modules due to missing unresolved libraries. Below I show three types of errors one get get and by fixing the environment in a proper place one can get rid of them all:

```
$ export PATH=$HOME/10xgenomics/cellranger-7.1.0/bin:$HOME/10xgenomics/cellranger-7.1.0/external/anaconda/bin:$HOME/10xgenomics/cellranger-7.1.0/lib/bin:$HOME/10xgenomics/cellranger-7.1.0/external/martian/bin:$PATH
export PYTHONPATH=$HOME/10xgenomics/cellranger-7.1.0/external/lib/python:$HOME/10xgenomics/cellranger-7.1.0/external/anaconda/lib/python3.9:$HOME/10xgenomics/cellranger-7.1.0/external/anaconda/lib/python3.9/site-packages:$HOME/10xgenomics/cellranger-7.1.0/external/martian/adapters/python:$HOME/10xgenomics/cellranger-7.1.0/lib/python:$HOME/10xgenomics/cellranger-7.1.0/external/anaconda/lib:"$PYTHONPATH"
$
$ cellranger testrun --id tiny3 --jobmode=torque 
Martian Runtime - v4.0.10
Serving UI at http://skirit.ics.muni.cz:43419?auth=MzbQsyuNnHfUlNwnnaqwGYIs77UigtPkthAba1dza5A

Running preflight checks (please wait)...
Checking sample info...
Checking FASTQ folder...
Checking reference...
Checking reference_path (/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/cellranger_tiny_ref) on skirit.ics.muni.cz...
Checking optional arguments...
mro: v4.0.10
mrp: v4.0.10
Anaconda: Python 3.9.7
numpy: 1.22.3
scipy: 1.9.1
pysam: 0.17.0
h5py: 3.6.0
pandas: 1.3.5
STAR: 2.7.2a
samtools: samtools 1.12

[error] Pipestance failed. Error log at:
tiny3/SC_RNA_COUNTER_CS/CELLRANGER_PREFLIGHT/fork0/chnk0-ub1d312edb5/_errors

Log message:
Traceback (most recent call last):
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/martian/adapters/python/martian_shell.py", line 454, in __init__
    self._module = __import__(os.path.basename(stagecode_path))
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/mro/rna/stages/common/cellranger_preflight/__init__.py", line 8, in <module>
    import cellranger.preflight as cr_preflight
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/lib/python/cellranger/preflight.py", line 16, in <module>
    import cellranger.reference as cr_reference
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/lib/python/cellranger/reference.py", line 23, in <module>
    import cellranger.cr_io as cr_io
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/lib/python/cellranger/cr_io.py", line 16, in <module>
    import lz4.frame as lz4
ModuleNotFoundError: No module named 'lz4'


Waiting 6 seconds for UI to do final refresh.
Pipestance failed. Use --noexit option to keep UI running after failure.

2023-03-16 11:22:05 Shutting down.
Saving pipestance info to "tiny3/tiny3.mri.tgz"
For assistance, upload this file to 10x Genomics by running:

cellranger upload <your_email> "tiny3/tiny3.mri.tgz"

$
```

```
$ cat /mnt/metacentrum/brno2-cerit/10xgenomics/bug_missing_pyfaidx.txt 
$ cellranger mkfastq --id=tutorial_walk_through --run=cellranger-tiny-bcl-1.2.0 --csv=cellranger-tiny-bcl-simple-1.2.0.csv --jobmode=torque 
/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/bin
cellranger mkfastq (cellranger-7.1.0)
Copyright (c) 2021 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------

Martian Runtime - v4.0.10
Serving UI at http://skirit.ics.muni.cz:41925?auth=vwWfcGm9TaPKBsUWL6A_KG8ppPdzjq502rhaJ6MVhNE

Running preflight checks (please wait)...
Checking run folder...
Checking RunInfo.xml...
Checking system environment...
Emitting run information...
Checking read specification...
Checking samplesheet specs...

[error] Pipestance failed. Error log at:
tutorial_walk_through/MAKE_FASTQS_CS/MAKE_FASTQS/MAKE_FASTQS_PREFLIGHT/fork0/chnk0-u1ae2130c87/_errors

Log message:
Traceback (most recent call last):
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/martian/adapters/python/martian_shell.py", line 454, in __init__
    self._module = __import__(os.path.basename(stagecode_path))
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/mro/tenkit/stages/make_fastqs/make_fastqs_preflight/__init__.py", line 15, in <module>
    import tenkit.preflight as tk_preflight
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/lib/python/tenkit/preflight.py", line 21, in <module>
    import tenkit.reference
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/lib/python/tenkit/reference.py", line 8, in <module>
    from common.pyfasta import FastaIndexed
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/lib/python/common/pyfasta.py", line 10, in <module>
    import pyfaidx
ModuleNotFoundError: No module named 'pyfaidx'


Waiting 6 seconds for UI to do final refresh.
Pipestance failed. Use --noexit option to keep UI running after failure.

2023-03-16 13:33:37 Shutting down.
Saving pipestance info to "tutorial_walk_through/tutorial_walk_through.mri.tgz"
For assistance, upload this file to 10x Genomics by running:

cellranger upload <your_email> "tutorial_walk_through/tutorial_walk_through.mri.tgz"


$ ../cellranger-7.1.0/external/anaconda/bin/python
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyfaidx
>>> import lz4
>>> dir(lz4)
['VERSION', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_version', 'library_version_number', 'library_version_string', 'version']
>>> lz4.__path__
['/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/anaconda/lib/python3.9/site-packages/lz4']
>>> pyfaidx.__path__
['/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/anaconda/lib/python3.9/site-packages/pyfaidx']
>>> 
$ 

$ find ../cellranger-7.1.0/ -name pyfaidx*
../cellranger-7.1.0/external/anaconda/lib/python3.9/site-packages/pyfaidx
../cellranger-7.1.0/external/anaconda/lib/python3.9/site-packages/pyfaidx-0.7.1.dist-info
$


023-03-16 14:42:22 [environ] TENX_SUBCMD=mkfastq
2023-03-16 14:42:22 [environ] TENX_PRODUCT=cellranger
2023-03-16 14:42:22 [environ] PATH=/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/lib/bin:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/martian/bin:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/anaconda/bin:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/bin/tenkit:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/bin:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/lib/bin:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/martian/bin:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/anaconda/bin:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/bin/tenkit:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/bin:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/lib/bin:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/martian/bin:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/anaconda/bin:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/bin/tenkit:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/bin:/cvmfs/software.metacentrum.cz/spack1/software/openjdk/linux-debian9-x86_64/11.0.2-gcc-qr7kxv/bin:/software/bcl2fastq2/2.2.0/bin:/storage/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0:/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0:/storage/brno3-cerit/home/mmokrejs/gentoo:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/software/meta-utils/public:/usr/bin
2023-03-16 14:42:22 [environ] RUST_BACKTRACE=1
2023-03-16 14:42:22 [environ] SSH_TTY=/dev/pts/187
2023-03-16 14:42:22 [environ] TENX_COPYRIGHT=Copyright (c) 2021 10x Genomics, Inc.  All rights reserved.
2023-03-16 14:42:22 [environ] BASH_FUNC_module%%=() {  eval `/software/modules/3.2.10/Modules/$MODULE_VERSION/bin/modulecmd bash $*`
}
2023-03-16 14:42:22 [environ] _=/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/martian/bin/mrp
2023-03-16 14:42:22 [options] --localcores=12
2023-03-16 14:42:22 [environ] MROPATH=/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/mro
2023-03-16 14:42:22 [version] MRO Version=cellranger-7.1.0
2023-03-16 14:42:22 [options] --jobmode=torque
2023-03-16 14:42:22 [options] --maxjobs=64
2023-03-16 14:42:22 [options] --jobinterval=100
2023-03-16 14:42:22 [options] --vdrmode=rolling
2023-03-16 14:42:22 [options] --profile=disable
2023-03-16 14:42:22 [options] --stackvars=false
2023-03-16 14:42:22 [options] --zip=false
2023-03-16 14:42:22 [options] --limit-loadavg=false
2023-03-16 14:42:22 [options] --noexit=false
2023-03-16 14:42:22 [options] --nopreflight=false
2023-03-16 14:42:22 [jobmngr] Job config = /auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/martian/jobmanagers/config.json
2023-03-16 14:42:22 [jobmngr] Using 12 cores, per --localcores option.
2023-03-16 14:42:22 [jobmngr] Using 1 GB for local jobs.
2023-03-16 14:42:22 [jobmngr] Job submit command = qsub
2023-03-16 14:42:22 [jobmngr] Job submit resources option = 
2023-03-16 14:42:22 [jobmngr] Job template = /auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/martian/jobmanagers/torque.template

...

[error] Pipestance failed. Error log at:
tutorial_walk_through/MAKE_FASTQS_CS/MAKE_FASTQS/MAKE_FASTQS_PREFLIGHT/fork0/chnk0-u23f9131cbe/_errors

Log message:
Traceback (most recent call last):
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/martian/adapters/python/martian_shell.py", line 454, in __init__
    self._module = __import__(os.path.basename(stagecode_path))
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/mro/tenkit/stages/make_fastqs/make_fastqs_preflight/__init__.py", line 15, in <module>
    import tenkit.preflight as tk_preflight
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/lib/python/tenkit/preflight.py", line 21, in <module>
    import tenkit.reference
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/lib/python/tenkit/reference.py", line 8, in <module>
    from common.pyfasta import FastaIndexed
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/lib/python/common/pyfasta.py", line 10, in <module>
    import pyfaidx
ModuleNotFoundError: No module named 'pyfaidx'
```

```
$ strace -v -f -s 4096 -o ../error.log2 cellranger mkfastq --id=tutorial_walk_through --run=cellranger-tiny-bcl-1.2.0 --csv=cellranger-tiny-bcl-simple-1.2.0.csv --jobmode=torque 
/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/bin
cellranger mkfastq (cellranger-7.1.0)
Copyright (c) 2021 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------

Martian Runtime - v4.0.10
2023-03-16 17:49:42 [runtime] Reattaching in torque mode.
Serving UI at http://skirit.ics.muni.cz:38259?auth=kgmVwMPIgdxSSKiRPmKTaJnllTmV8QBdsONEgzeaXs8

2023-03-16 17:49:42 [runtime] (reset-partial)   ID.tutorial_walk_through.MAKE_FASTQS_CS.MAKE_FASTQS.MAKE_FASTQS_PREFLIGHT.fork0.chnk0

[error] Pipestance failed. Error log at:
tutorial_walk_through/MAKE_FASTQS_CS/MAKE_FASTQS/MAKE_FASTQS_PREFLIGHT/fork0/chnk0-u99781348a6/_errors

Log message:
Traceback (most recent call last):
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/external/martian/adapters/python/martian_shell.py", line 454, in __init__
    self._module = __import__(os.path.basename(stagecode_path))
  File "/auto/brno2/home/mmokrejs/10xgenomics/cellranger-7.1.0/mro/tenkit/stages/make_fastqs/make_fastqs_preflight/__init__.py", line 12, in <module>
    from six import ensure_str
ModuleNotFoundError: No module named 'six'
```

*Testcase:*
`cellranger count --id=run_count_1kpbmcs  --fastqs=pbmc_1k_v3_fastqs  --sample=pbmc_1k_v3  --transcriptome=../cellranger-7.1.0/refdata-gex-GRCh38-2020-A --jobmode=torque`

*Fix template file (likewise fix a pbspro template file too!):*
[torque.template.txt](https://github.com/10XGenomics/cellranger/files/11623818/torque.template.txt)

*A workaround:*
The *workaround* is to rename `martian_shell.py` to `martian_shell.py.ori` and create in place of `martian_shell.py` a shellscript which sets proper environment `PYTHONPATH` and `LD_LIBRARY_PATH` and then calls `martian_shell.py.ori`.

```
cellranger-7.1.0/external/martian/adapters/python/martian_shell.py
#!/usr/bin/env bash

# https://stackoverflow.com/questions/23244418/set-ld-library-path-before-importing-in-python

export LD_LIBRARY_PATH=$HOME/10xgenomics/cellranger-7.1.0/external/anaconda/lib

export PYTHONPATH=$HOME/10xgenomics/cellranger-7.1.0/external/lib/python:$HOME/10xgenomics/cellranger-7.1.0/external/anaconda/lib/python3.9:$HOME/10xgenomics/cellranger-7.1.0/external/anaconda/lib/python3.9/site-packages:$HOME/10xgenomics/cellranger-7.1.0/external/martian/adapters/python:$HOME/10xgenomics/cellranger-7.1.0/lib/python:$HOME/10xgenomics/cellranger-7.1.0/external/anaconda/lib

printenv | grep GOMAXPROCS
printenv | grep MKL_NUM_THREADS
printenv | grep MRO_UUID
printenv | grep NUMEXPR_MAX_THREADS
printenv | grep NUMEXPR_NUM_THREADS
printenv | grep OMP_NUM_THREADS

echo "$HOME/10xgenomics/cellranger-7.1.0/external/anaconda/bin/python3.9 -x $HOME/10xgenomics/cellranger-7.1.0/external/martian/adapters/python/martian_shell.py.ori $@"

# export GOMAXPROCS=1   MKL_NUM_THREADS=1   MRO_UUID=ffac4f02-8eec-4f49-ad91-bdcc723374c2   NUMEXPR_MAX_THREADS=1   NUMEXPR_NUM_THREADS=1   OMP_NUM_THREADS=1

$HOME/10xgenomics/cellranger-7.1.0/external/anaconda/bin/python3.9 -x $HOME/10xgenomics/cellranger-7.1.0/external/martian/adapters/python/martian_shell.py.ori "$@"
```

I think the bug actually affects all cluster managers, not *just* `torque` and `pbspro`. This is likely also applicable to longranger.

**Comment by adam-azarchs** [comment]
You don't need to modify `martian_shell.py`.  Just modify your `torque.template` to add the `-V` flag to ensure environment variables from the submit host are propagated to the job.  See the example template https://github.com/martian-lang/martian/blob/8485e42901a4ad44b84e71d8b384ca0cd786ed1d/jobmanagers/torque.template.example#L21

**Comment by adam-azarchs** [comment]
Also, you may need to check that you don't have a `.bashrc` that is making changes to the environment.  We recommend that you put such things in `.bash_profile` instead so that they take effect when starting a new login session but not every time a new shell is started.  Alternatively you can modify the job template to run the shell with `--norc`, which is the default when using `sh` rather than `bash`.

**Comment by mmokrejs** [comment]
Thank you for the response but I tried `-V` before and that was NOT helpful.

Also, my `.bashrc` is empty and `.bash_profile` contains unrelated variables. Anyway, martians are zapping all env variables set in my running bash used to submit a job and then again, when job child is executed under `PBS`.

**Comment by adam-azarchs** [comment]
Martian does not modify the environment.  If PBS isn't correctly propagating environment variables, my suggestion there would be to add a line to `source` the `sourceme.bash` in the job template.

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
