### ISSUE TITLE
CellRanger-ARC for Arbidosis failed with error

### ISSUE THREAD

**Issue by nilesh-iiita** [10XGenomics/cellranger#220]
I am running CellRanger-ARC for Arabidopsis and I am getting the following error:

```
2023-06-02 14:40:02 [runtime] (failed)          ID.D3.SC_ATAC_GEX_COUNTER_CS.SC_ATAC_GEX_COUNTER._SC_ATAC_GEX_ANALYZER._PEAK_ANNOTATOR.ANNOTATE_PEAKS

[error] Pipestance failed. Error log at:
D3/SC_ATAC_GEX_COUNTER_CS/SC_ATAC_GEX_COUNTER/_SC_ATAC_GEX_ANALYZER/_PEAK_ANNOTATOR/ANNOTATE_PEAKS/fork0/join-uc5dd7a4574/_errors

Log message:
Traceback (most recent call last):
File "/data/rc/apps/rc/software/CellRanger-ARC/2.0.0/external/martian/adapters/python/martian_shell.py", line 659, in _main
stage.main()
File "/data/rc/apps/rc/software/CellRanger-ARC/2.0.0/external/martian/adapters/python/martian_shell.py", line 629, in main
lambda: self._module.join(args, outs, chunk_defs, chunk_outs)
File "/data/rc/apps/rc/software/CellRanger-ARC/2.0.0/external/martian/adapters/python/martian_shell.py", line 589, in _run
cmd()
File "/data/rc/apps/rc/software/CellRanger-ARC/2.0.0/external/martian/adapters/python/martian_shell.py", line 629, in <lambda>
lambda: self._module.join(args, outs, chunk_defs, chunk_outs)
File "/data/rc/apps/rc/software/CellRanger-ARC/2.0.0/mro/atac/stages/analysis/annotate_peaks/init.py", line 105, in join
gene_id_name_map = build_gene_id_name_map(ref_mgr)
File "/data/rc/apps/rc/software/CellRanger-ARC/2.0.0/mro/atac/stages/analysis/annotate_peaks/init.py", line 60, in build_gene_id_name_map
fields.attrs.get("gene_name", fields.attrs["gene_id"])
File "pybedtools/cbedtools.pyx", line 392, in pybedtools.cbedtools.Interval.attrs.get
File "pybedtools/cbedtools.pyx", line 180, in pybedtools.cbedtools.Attributes.init
ValueError: need more than 1 value to unpack
```

I have tried the following to resolve the issue:

I have updated CellRanger-ARC to the latest version.
I have checked the input data to make sure that it is in the correct format.
I have checked the software used to run CellRanger-ARC to make sure that it is up to date and that it has all of the necessary dependencies.
I am still unable to resolve the issue.

Please help me to troubleshoot this issue.

Thank you.

**Comment by RosaDeSa** [comment]
I have the same errors. Did you solve it?

**Comment by Yihui-Zhu** [comment]
We have saw this error `ValueError: need more than 1 value to unpack` before, this error is usually related with GTF format.

Some formatting tips to use:
- retain only `gene_id` & `transcript_id` attributes (#can include gene_names if needed)
- replace/remove the empty `gene_id` entries
- duplicate `transcripts_ids` for multiple gene_ids have to be converted as unique
- Remove semi colons after `gene_name` and avoid bloated col9 in the GTF (extraneous information in this col can cause parsing issues)
More details can be found on our support site: https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/pipelines/latest/advanced/references.

We have high successful rate using Ensembl reference. Here is the link for reference  http://ftp.ebi.ac.uk/ensemblgenomes/pub/release-51/plants/fasta/arabidopsis_thaliana/dna/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa.gz
http://ftp.ebi.ac.uk/ensemblgenomes/pub/release-51/plants/gtf/arabidopsis_thaliana/Arabidopsis_thaliana.TAIR10.51.gtf.gz
If there are more questions, feel free to email us at [support@10xgenomics.com](mailto:support@10xgenomics.com)

**Comment by RosaDeSa** [comment]
Thanks for the answer, actually I’m working on human data not Arabidopsis and  I’m using cellranger arc reference hg38.
I’ve this error:

File "/opt/cellranger-arc-2.0.2/external/martian/adapters/python/martian_shell.py", line 659, in _main
      stage.main()
    File "/opt/cellranger-arc-2.0.2/external/martian/adapters/python/martian_shell.py", line 618, in main
      self._run(lambda: self._module.main(args, outs))
    File "/opt/cellranger-arc-2.0.2/external/martian/adapters/python/martian_shell.py", line 589, in _run
      cmd()
    File "/opt/cellranger-arc-2.0.2/external/martian/adapters/python/martian_shell.py", line 618, in <lambda>
      self._run(lambda: self._module.main(args, outs))
    File "/opt/cellranger-arc-2.0.2/mro/atac_rna/stages/preflight/arc_counter_preflight/__init__.py", line 114, in main
      cr_preflight.record_package_versions()
    File "/opt/cellranger-arc-2.0.2/lib/python/cellranger/preflight.py", line 348, in record_package_versions
      version = tk_subproc.check_output(cmd)
    File "/opt/cellranger-arc-2.0.2/lib/python/tenkit/log_subprocess.py", line 76, in check_output
      return subprocess.check_output(args, *wargs, **kwargs)
    File "/opt/cellranger-arc-2.0.2/external/anaconda/lib/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout

**Comment by Yihui-Zhu** [comment]
For human, we have our prebuild reference here: https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/downloads/latest. The build step is here: https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/release-notes/references#GRCh38-2020-A-2.0.0. Feel free to send us an email, so we can help more on your specific case.

**Comment by RosaDeSa** [comment]
Thanks for shortly reply, I’ll check it out tomorrow! Il giorno 9 giu 2023, alle ore 23:22, Yihui Zhu ***@***.***> ha scritto:﻿
For human, we have our prebuild reference here: https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/downloads/latest. The build step is here: https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/release-notes/references#GRCh38-2020-A-2.0.0. Feel free to send us an email, so we can help more on your specific case.

**Comment by RosaDeSa** [comment]
I used the reference GRCh38-2020-A-2.0.0 and I have the error aforementioned

**Comment by RosaDeSa** [comment]
I used the recommended reference "refdata-cellranger-arc-GRCh38-2020-A-2.0.0.tar.gz."
My error is 

`Log message:
  Traceback (most recent call last):
    File "/opt/cellranger-arc-2.0.2/external/martian/adapters/python/martian_shell.py", line 659, in _main
      stage.main()
    File "/opt/cellranger-arc-2.0.2/external/martian/adapters/python/martian_shell.py", line 618, in main
      self._run(lambda: self._module.main(args, outs))
    File "/opt/cellranger-arc-2.0.2/external/martian/adapters/python/martian_shell.py", line 589, in _run
      cmd()
    File "/opt/cellranger-arc-2.0.2/external/martian/adapters/python/martian_shell.py", line 618, in <lambda>
      self._run(lambda: self._module.main(args, outs))
    File "/opt/cellranger-arc-2.0.2/mro/atac_rna/stages/preflight/arc_counter_preflight/__init__.py", line 114, in main
      cr_preflight.record_package_versions()
    File "/opt/cellranger-arc-2.0.2/lib/python/cellranger/preflight.py", line 348, in record_package_versions
      version = tk_subproc.check_output(cmd)
    File "/opt/cellranger-arc-2.0.2/lib/python/tenkit/log_subprocess.py", line 76, in check_output
      return subprocess.check_output(args, *wargs, **kwargs)
    File "/opt/cellranger-arc-2.0.2/external/anaconda/lib/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout
    File "/opt/cellranger-arc-2.0.2/external/anaconda/lib/python3.7/subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['python', '-c', 'import numpy; print(numpy.__version__)']' returned non-zero exit status 1.
  `

**Comment by nilesh-iiita** [comment]
The Gene name in Arabidopsis is inappropriate, so I replaced each gene/symbol name with AGI IDs, and it worked! Using AGI IDs can help ensure consistency and accuracy when working with gene names in Arabidopsis.

**Comment by Yihui-Zhu** [comment]
Hi @RosaDeSa, since your case is human, this is a different case, please email us at support@10xgenomics.com, so we can help you on your case. Thanks!

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
