### ISSUE TITLE
Cellranger-arc peak annotation error - bedtools

### ISSUE THREAD

**Issue by yigitbabal** [10XGenomics/cellranger#224]
Hello, 

I am trying to run cellranger-arc count by custom reference genome. cellranger-arc mkref worked very well. However I am getting an error during cellranger-arc count during peak annotation. How can I solve this error, do you know anything about that? 

Best regards,
Yigit

Error log:

2023-08-18 00:59:21 [runtime] (failed)          ID.acomys.SC_ATAC_GEX_COUNTER_CS.SC_ATAC_GEX_COUNTER._SC_ATAC_GEX_ANALYZER._PEAK_ANNOTATOR.ANNOTATE_PEAKS

[error] Pipestance failed. Error log at:
acomys/SC_ATAC_GEX_COUNTER_CS/SC_ATAC_GEX_COUNTER/_SC_ATAC_GEX_ANALYZER/_PEAK_ANNOTATOR/ANNOTATE_PEAKS/fork0/chnk02-u04c6dea638/_errors

Log message:
Traceback (most recent call last):
  File "/crex/proj/spatialals/workspace/ykbabal/cellranger-arc-2.0.2/external/martian/adapters/python/martian_shell.py", line 659, in _main
    stage.main()
  File "/crex/proj/spatialals/workspace/ykbabal/cellranger-arc-2.0.2/external/martian/adapters/python/martian_shell.py", line 618, in main
    self._run(lambda: self._module.main(args, outs))
  File "/crex/proj/spatialals/workspace/ykbabal/cellranger-arc-2.0.2/external/martian/adapters/python/martian_shell.py", line 589, in _run
    cmd()
  File "/crex/proj/spatialals/workspace/ykbabal/cellranger-arc-2.0.2/external/martian/adapters/python/martian_shell.py", line 618, in <lambda>
    self._run(lambda: self._module.main(args, outs))
  File "/crex/proj/spatialals/workspace/ykbabal/cellranger-arc-2.0.2/mro/atac/stages/analysis/annotate_peaks/__init__.py", line 73, in main
    annotations = annotate_peaks(peak_chunk, args.reference_path)
  File "/crex/proj/spatialals/workspace/ykbabal/cellranger-arc-2.0.2/lib/python/atac/analysis/annotation.py", line 198, in annotate_peaks
    transcripts_filtered, wa=True, wb=True
  File "/crex/proj/spatialals/workspace/ykbabal/cellranger-arc-2.0.2/external/anaconda/lib/python3.7/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/crex/proj/spatialals/workspace/ykbabal/cellranger-arc-2.0.2/external/anaconda/lib/python3.7/site-packages/pybedtools/bedtool.py", line 401, in wrapped
    decode_output=decode_output,
  File "/crex/proj/spatialals/workspace/ykbabal/cellranger-arc-2.0.2/external/anaconda/lib/python3.7/site-packages/pybedtools/helpers.py", line 460, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools intersect -wb -wa -b /proj/spatialals/Acomys/multiome_updated/acomys/SC_ATAC_GEX_COUNTER_CS/SC_ATAC_GEX_COUNTER/_SC_ATAC_GEX_ANALYZER/_PEAK_ANNOTATOR/ANNOTATE_PEAKS/fork0/chnk02-u04c6dea638/tmp/pybedtools.9_m9igl3.tmp -a /proj/spatialals/Acomys/multiome_updated/acomys/SC_ATAC_GEX_COUNTER_CS/SC_ATAC_GEX_COUNTER/_SC_ATAC_GEX_ANALYZER/_PEAK_ANNOTATOR/ANNOTATE_PEAKS/fork0/chnk02-u04c6dea638/tmp/pybedtools.emea0no1.tmp

Error message was:
Error: line number 548 of file /proj/spatialals/Acomys/multiome_updated/acomys/SC_ATAC_GEX_COUNTER_CS/SC_ATAC_GEX_COUNTER/_SC_ATAC_GEX_ANALYZER/_PEAK_ANNOTATOR/ANNOTATE_PEAKS/fork0/chnk02-u04c6dea638/tmp/pybedtools.emea0no1.tmp has 4 fields, but 5 were expected.

**Comment by evolvedmicrobe** [comment]
Please send this issue to support@10xgenomics.com and someone will follow up with you.

**Comment by schnappi-wkl** [comment]
Hi Yigit,
Have you solved it? i also encoutered this error?
