### ISSUE TITLE
cellranger 7.0.0 pipestance failed, when executing feature barcode

### ISSUE THREAD

**Issue by sagrikachugh** [10XGenomics/cellranger#230]
I am trying to run Gene expression with antibody capture and get the following error, Could anyone please help how to solve this?
Please note I am using version 7.0.1 not 7.0.0 as stated in the title.
Also, I have downloaded the mouse reference genome from cellranger website, I assume there is some issue with the gene index but I am not sure how to approach this error to solve it.

Here is my log:

Martian Runtime - v4.0.8
2023-09-15 14:53:48 [jobmngr] WARNING: User-supplied amount 100 GB is higher than the detected cgroup memory limit of 60.3 GB
Serving UI at http://scgn08.svi.edu.au:38871?auth=RmZ4nvPW_DJvM0gaEIOWvMeFNQopulAublW_iPlMY3A

Running preflight checks (please wait)...
Checking feature definition file...
Checking sample info...
Checking FASTQ folder...
Checking reference...
Checking reference_path (/mnt/beegfs/mccarthy/backed_up/general/schugh/Projects/Purton_lab/reference_genome/mm10-new/refdata-gex-mm10-2020-A) on scgn08.svi.edu.au...
Checking optional arguments...
mro: v4.0.8
mrp: v4.0.8
Anaconda: Python 3.8.12
numpy: 1.21.2
scipy: 1.7.3
pysam: 0.16.0.1

[error] Pipestance failed. Error log at:
svi_sample1/SC_RNA_COUNTER_CS/CELLRANGER_PREFLIGHT/fork0/chnk0-u18b403e35f/_errors

Log message:
Traceback (most recent call last):
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/lib/python/cellranger/reference.py", line 655, in load_from_reference
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/external/anaconda/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/external/anaconda/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '[b'/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/lib/bin/gtf_to_gene_index', b'/mnt/beegfs/mccarthy/backed_up/general/schugh/Projects/Purton_lab/reference_genome/mm10-new/refdata-gex-mm10-2020-A', b'gene_index.json']' returned non-zero exit status 101.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/external/martian/adapters/python/martian_shell.py", line 680, in _main
    stage.main()
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/external/martian/adapters/python/martian_shell.py", line 639, in main
    self._run(lambda: self._module.main(args, outs))
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/external/martian/adapters/python/martian_shell.py", line 596, in _run
    cmd()
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/external/martian/adapters/python/martian_shell.py", line 639, in <lambda>
    self._run(lambda: self._module.main(args, outs))
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/mro/rna/stages/common/cellranger_preflight/__init__.py", line 60, in main
    run_preflight_checks(args)
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/mro/rna/stages/common/cellranger_preflight/__init__.py", line 34, in run_preflight_checks
    cr_preflight.check_sample_info(
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/lib/python/cellranger/preflight.py", line 633, in check_sample_info
    feature_ref = try_load_feature_ref(reference_path, feature_ref_path)
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/lib/python/cellranger/preflight.py", line 312, in try_load_feature_ref
    feature_ref = rna_feature_ref.from_transcriptome_and_csv(
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/lib/python/cellranger/rna/feature_ref.py", line 269, in from_transcriptome_and_csv
    gene_index = cr_reference.NewGeneIndex.load_from_reference(gene_ref_path)
  File "/mnt/beegfs/users/schugh/cellranger/cellranger-7.0.1/lib/python/cellranger/reference.py", line 657, in load_from_reference
    raise RuntimeError("couldn't load reference info: " + ensure_str(exc.output)) from exc
RuntimeError: couldn't load reference info: thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1492`: Expected a transcript length of 1492, but got 0 stitching the exons for Transcript {
    idx: TranscriptIdx(
        2706,
    ),
    gene_idx: GeneIdx(
        667,
    ),
    id: "ENSMUST00000160792",
    chrom: "chr1",
    strand: Reverse,
    exons: [
        Exon {
            start: 85088406,
            end: 85088816,
        },
        Exon {
            start: 85089526,
            end: 85089580,
      },
        Exon {
            start: 85091076,
            end: 85091189,
        },
        Exon {
            start: 85094296,
            end: 85094359,
        },
        Exon {
            start: 85099476,
            end: 85099648,
        },
        Exon {
            start: 85100531,
            end: 85100694,
        },
        Exon {
            start: 85109336,
            end: 85109853,
        },
    ],
    properties: [
        (
            "gene_id",
            "ENSMUSG00000089844",
        ),
        (
            "gene_version",
            "7",
        ),
        (
            "transcript_id",
            "ENSMUST00000160792",
        ),
        (
            "transcript_version",
            "7",
        ),
        (
            "gene_type",
            "protein_coding",
        ),
        (
            "gene_name",
            "A530032D15Rik",
        ),
        (
            "transcript_type",
            "protein_coding",
        ),
        (
            "transcript_name",
            "A530032D15Rik-201",
        ),
        (
            "level",
            "2",
        ),
        (
            "protein_id",
            "ENSMUSP00000125122.1",
        ),
        (
            "transcript_support_level",
            "1",
        ),
        (
            "mgi_id",
            "MGI:3037746",
        ),
        (
            "tag",
            "basic",
        ),
(
            "tag",
            "appris_principal_2",
        ),
	(
            "tag",
            "CCDS",
        ),
	(
            "ccdsid",
            "CCDS15107.1",
        ),
	(
            "havana_gene",
            "OTTMUSG00000029176.35",
        ),
	(
            "havana_transcript",
            "OTTMUST00000072362.3",
        ),
    ],
}', execroot/exec/lib/rust/transcriptome/src/transcriptome.rs:63:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:154:5
   4: transcriptome::transcriptome::Transcript::get_sequence
             at execroot/exec/lib/rust/execroot/exec/lib/rust/transcriptome/src/transcriptome.rs:63:9
   5: transcriptome::transcriptome::Transcript::gc_content
             at execroot/exec/lib/rust/execroot/exec/lib/rust/transcriptome/src/transcriptome.rs:84:9
   6: transcriptome::python_gene_index::python_gene_index
             at execroot/exec/lib/rust/execroot/exec/lib/rust/transcriptome/src/python_gene_index.rs:122:26
   7: transcriptome::python_gene_index::generate_gene_index
             at execroot/exec/lib/rust/execroot/exec/lib/rust/transcriptome/src/python_gene_index.rs:217:13
   8: transcriptome::python_gene_index::write_gene_index
             at execroot/exec/lib/rust/execroot/exec/lib/rust/transcriptome/src/python_gene_index.rs:254:13
   9: gtf_to_gene_index::main
             at execroot/exec/lib/rust/transcriptome/src/bin/gtf_to_gene_index.rs:23:15
  10: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Waiting 6 seconds for UI to do final refresh.
h5py: 3.6.0
pandas: 1.3.5
STAR: 2.7.2a
samtools: samtools 1.12
Pipestance failed. Use --noexit option to keep UI running after failure.

2023-09-15 14:54:33 Shutting down.
Saving pipestance info to "svi_sample1/svi_sample1.mri.tgz"
For assistance, upload this file to 10x Genomics by running:

Any help would be appreciated, thanks

**Comment by sagrikachugh** [comment]
I tried using version 7.1.0 but still run into error as below

Martian Runtime - v4.0.10
2023-09-15 15:27:58 [jobmngr] WARNING: User-supplied amount 100 GB is higher than the detected cgroup memory limit of 60.3 GB
Serving UI at http://scgn01.svi.edu.au:33817?auth=clzUggAlKWhKqu5boKRPNaQQQHzJUfGkTYNkkG_XuFU

Running preflight checks (please wait)...
Checking feature definition file...
Checking sample info...
Checking FASTQ folder...
Checking reference...
Checking reference_path (/mnt/beegfs/mccarthy/backed_up/general/schugh/Projects/Purton_lab/reference_genome/mm10-new/refdata-gex-mm10-2020-A) on scgn01.svi.edu.au...
Checking optional arguments...
mro: v4.0.10
mrp: v4.0.10
Anaconda: Python 3.9.7
numpy: 1.22.3
scipy: 1.9.1
pysam: 0.17.0
h5py: 3.6.0

[error] Pipestance failed. Error log at:
svi_sample1/SC_RNA_COUNTER_CS/CELLRANGER_PREFLIGHT/fork0/chnk0-u5a2203eb61/_errors

Log message:
Traceback (most recent call last):
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/lib/python/cellranger/reference.py", line 656, in load_from_reference
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/external/anaconda/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/external/anaconda/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '[b'/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/lib/bin/gtf_to_gene_index', b'/mnt/beegfs/mccarthy/backed_up/general/schugh/Projects/Purton_lab/reference_genome/mm10-new/refdata-gex-mm10-2020-A', b'gene_index.json']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/external/martian/adapters/python/martian_shell.py", line 648, in _main
    stage.main()
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/external/martian/adapters/python/martian_shell.py", line 607, in main
    self._run(lambda: self._module.main(args, outs))
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/external/martian/adapters/python/martian_shell.py", line 564, in _run
    cmd()
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/external/martian/adapters/python/martian_shell.py", line 607, in <lambda>
    self._run(lambda: self._module.main(args, outs))
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/mro/rna/stages/common/cellranger_preflight/__init__.py", line 60, in main
    run_preflight_checks(args)
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/mro/rna/stages/common/cellranger_preflight/__init__.py", line 34, in run_preflight_checks
    cr_preflight.check_sample_info(
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/lib/python/cellranger/preflight.py", line 673, in check_sample_info
    feature_ref = try_load_feature_ref(reference_path, feature_ref_path)
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/lib/python/cellranger/preflight.py", line 320, in try_load_feature_ref
    feature_ref = rna_feature_ref.from_transcriptome_and_csv(
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/lib/python/cellranger/rna/feature_ref.py", line 296, in from_transcriptome_and_csv
    gene_index = cr_reference.NewGeneIndex.load_from_reference(gene_ref_path)
  File "/mnt/beegfs/users/schugh/opt/cellranger-7.1.0/lib/python/cellranger/reference.py", line 658, in load_from_reference
    raise RuntimeError("couldn't load reference info: " + ensure_str(exc.output)) from exc
RuntimeError: couldn't load reference info: Bad address (os error 14)



Waiting 6 seconds for UI to do final refresh.
Pipestance failed. Use --noexit option to keep UI running after failure.

2023-09-15 15:28:37 Shutting down.
2023-09-15 15:28:37 Caught signal terminated
2023-09-15 15:28:37 [monitor] Caught signal terminated
Saving pipestance info to "svi_sample1/svi_sample1.mri.tgz"
For assistance, upload this file to 10x Genomics by running:

**Comment by evolvedmicrobe** [comment]
Hi, please reach out to support@10xgenomics.com, they'll be able to help you and access your uploaded file with diagnostic information.

**Comment by sagrikachugh** [comment]
I did upload a file earlier and haven't received a response yet, I haven't uploaded any file this time and posted my issue here, do you suggest I should again try uploading my file?

**Comment by elehnert10x** [comment]
Our records show that a response was sent when you uploaded your file - it may have gone to you spam folder? If you are still having an issue and would like support, please reach out to [support@10xgenomics.com](mailto:support@10xgenomics.com).
