### ISSUE TITLE
cellranger aggr - edge case error

### ISSUE THREAD

**Issue by cchrysostomou** [10XGenomics/cellranger#36]
I have noticed what I believe to be an edge case bug when running the aggr program. In order for the bug to be observed, cellranger count has to be run on a transcriptome that has only one gene (one row). In this situation, cellranger aggr will raise the error listed below on molecular info files generated in cellranger count. I believe this is because, when performing the numpy operation on a dataset with a single column (only one gene), numpy returns an number rather than an array of shape (,1). Reshaping the array might fix this error. I confirmed that this error does not occur when passing in two genes to the transcriptome. 

```
Log message:
Traceback (most recent call last):
  File "/opt/cellranger-3.0.2/martian-cs/v3.2.0/adapters/python/martian_shell.py", line 590, in _main
    stage.main()
  File "/opt/cellranger-3.0.2/martian-cs/v3.2.0/adapters/python/martian_shell.py", line 561, in main
    self._run(lambda: self._module.join(
  File "/opt/cellranger-3.0.2/martian-cs/v3.2.0/adapters/python/martian_shell.py", line 524, in _run
    cmd()
  File "/opt/cellranger-3.0.2/martian-cs/v3.2.0/adapters/python/martian_shell.py", line 562, in <lambda>
    args, outs, chunk_defs, chunk_outs))
  File "/opt/cellranger-3.0.2/cellranger-cs/3.0.2/mro/stages/aggregator/check_invariants/__init__.py", line 103, in join
    if len(input_feature_counts[lib_gg]) != len(output_feature_counts[lib_gg]):
TypeError: len() of unsized object
```

**Comment by Janexty** [comment]
Hi,you fixed this problem. I encountered  the same error.

**Comment by Janexty** [comment]
Hi,you fixed this problem? I encountered the same error
