### ISSUE TITLE
cellranger vdj exist status 101

### ISSUE THREAD

**Issue by aqzas** [10XGenomics/cellranger#37]
hi, 
Does any meet the same problem ?
It looks like some issue in the subprocess
I have checked  md5, no problem founded,  any advise is ok

```Shell
[error] Pipestance failed. Error log at:
SRR8315772/SC_VDJ_ASSEMBLER_CS/SC_VDJ_ASSEMBLER/ASSEMBLE_VDJ/fork0/chnk29-u01581b59ef/_errors

Log message:
Traceback (most recent call last):
  File "/project/chensy/salyut/Tool/cellranger-3.0.2/martian-cs/v3.2.0/adapters/python/martian_shell.py", line 590, in _main
    stage.main()
  File "/project/chensy/salyut/Tool/cellranger-3.0.2/martian-cs/v3.2.0/adapters/python/martian_shell.py", line 555, in main
    self._run(lambda: self._module.main(args, outs))
  File "/project/chensy/salyut/Tool/cellranger-3.0.2/martian-cs/v3.2.0/adapters/python/martian_shell.py", line 524, in _run
    cmd()
  File "/project/chensy/salyut/Tool/cellranger-3.0.2/martian-cs/v3.2.0/adapters/python/martian_shell.py", line 555, in <lambda>
    self._run(lambda: self._module.main(args, outs))
  File "/project/chensy/salyut/Tool/cellranger-3.0.2/cellranger-cs/3.0.2/mro/stages/vdj/assemble_vdj/__init__.py", line 128, in main
    run_assembly(args.chunked_bam, martian.make_path(''), args)
  File "/project/chensy/salyut/Tool/cellranger-3.0.2/cellranger-cs/3.0.2/mro/stages/vdj/assemble_vdj/__init__.py", line 87, in run_assembly
    tk_subproc.check_call(cmd, cwd=os.getcwd())
  File "/project/chensy/salyut/Tool/cellranger-3.0.2/cellranger-cs/3.0.2/tenkit/lib/python/tenkit/log_subprocess.py", line 37, in check_call
    return subprocess.check_call(*args, **kwargs)
  File "/project/chensy/salyut/Tool/cellranger-3.0.2/miniconda-cr-cs/4.3.21-miniconda-cr-cs-c10/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['vdj_asm', 'asm', u'/project/chensy/benchmark/results/10X-scTCR/SRR8315772/SC_VDJ_ASSEMBLER_CS/SC_VDJ_ASSEMBLER/FILTER_VDJ_READS/fork0/chnk29-u01581b58cf/files/barcode_chunked_bams.bam', '/project/chensy/be
nchmark/results/10X-scTCR/SRR8315772/SC_VDJ_ASSEMBLER_CS/SC_VDJ_ASSEMBLER/ASSEMBLE_VDJ/fork0/chnk29-u01581b59ef/files/', '--kmers=2', '--min-contig=250', '--min-qual=2', '--score-factor=0.6', '--qual-factor=0.9', '--min-sw-score=50', '-
-rt-error=0.0001', '--min-umi-reads=556']' returned non-zero exit status 101
```

**Comment by honghh2018** [comment]
Hi @aqzas,
    should this issue done ? i meet with the same error when run scRNA data on sge's node?
    should any advices take for this issue?

**Comment by TrumanZYX** [comment]
I also have this question，maybe it's limit localmen???

**Comment by mpandela** [comment]
Bump. Would love an answer to why this happens

**Comment by apredeus** [comment]
Had similar issue - re-running the same job _from scratch_ (not using cached data) with a bit more RAM worked. Kept failing when I tried to use the cache though.
