### ISSUE TITLE
More strict parsing of GTF during mkref

### ISSUE THREAD

**Issue by lparsons** [10XGenomics/cellranger#39]
In Cell Ranger 3.x, we've run into an issue using reference genomes that work fine in 2.x. The issue occurs when there are two lines for a given `gene_id` and one line has a `gene_name` attribute and the other does not. During analysis, Cell Ranger 3.x ends up creating two records for these two lines since each have a different name, but later throwing an error since they are two records with the same id.

Example gtf lines
```
NC_004570   StringTie   transcript  4542    5039    1000    +   .   gene_id "MSTRG.12"; transcript_id "Cisavi.CG.ENS81.NC_004570.4542-5039.21034.t"; ref_gene_id "Cisavi.CG.ENS81.NC_004570.4542-5039"
NC_004570   StringTie   exon    4542    5039    1000    +   .   gene_id "MSTRG.12"; transcript_id "Cisavi.CG.ENS81.NC_004570.4542-5039.21034.t"; exon_number "1"; ref_gene_id "Cisavi.CG.ENS81.NC_004570.4542-5039"
NC_004570   StringTie   transcript  5019    5086    1000    +   .   gene_id "MSTRG.12"; transcript_id "Cisavi.mt-tRNA.ENS81.NC_004570.5019-5086.21035.t"; gene_name "Cisavi.mt-tRNA.ENS81.NC_004570.5019-5086"; ref_gene_id "Cisavi.mt-tRNA.ENS81.NC_004570.5019-5086"
NC_004570   StringTie   exon    5019    5086    1000    +   .   gene_id "MSTRG.12"; transcript_id "Cisavi.mt-tRNA.ENS81.NC_004570.5019-5086.21035.t"; exon_number "1"; gene_name "Cisavi.mt-tRNA.ENS81.NC_004570.5019-5086"; ref_gene_id "Cisavi.mt-tRNA.ENS81.NC_004570.5019-5086"
```

Example error
```
[error] Pipestance failed. Error log at:
chencao_cellranger_ensembl_stringtie_fix_10hpf_Cs/SC_RNA_COUNTER_CS/SC_RNA_COUNTER/_BASIC_SC_RNA_COUNTER/EXTRACT_READS/fork0/chnk00-u09384073d4/_errors

Log message:
Traceback (most recent call last):
  File "/Genomics/levineshare/People/Chen/tools/cellranger-3.1.0/martian-cs/v3.2.3/adapters/python/martian_shell.py", line 589, in _main
    stage.main()
  File "/Genomics/levineshare/People/Chen/tools/cellranger-3.1.0/martian-cs/v3.2.3/adapters/python/martian_shell.py", line 554, in main
    self._run(lambda: self._module.main(args, outs))
  File "/Genomics/levineshare/People/Chen/tools/cellranger-3.1.0/martian-cs/v3.2.3/adapters/python/martian_shell.py", line 523, in _run
    cmd()
  File "/Genomics/levineshare/People/Chen/tools/cellranger-3.1.0/martian-cs/v3.2.3/adapters/python/martian_shell.py", line 554, in <lambda>
    self._run(lambda: self._module.main(args, outs))
  File "/Genomics/levineshare/People/Chen/tools/cellranger-3.1.0/cellranger-cs/3.1.0/mro/stages/common/extract_reads/__init__.py", line 167, in main
    args.feature_reference)
  File "/Genomics/levineshare/People/Chen/tools/cellranger-3.1.0/cellranger-cs/3.1.0/lib/python/cellranger/rna/feature_ref.py", line 280, in from_transcriptome_and_csv
    return FeatureReference(feature_defs, all_tag_keys)
  File "/Genomics/levineshare/People/Chen/tools/cellranger-3.1.0/cellranger-cs/3.1.0/lib/python/cellranger/feature_ref.py", line 43, in __init__
    (this_fd_str, seen_fd_str))
FeatureDefException: Found two feature definitions with the same ID: (ID: MSTRG.12; name: Cisavi.mt-tRNA.ENS81.NC_004570.5019-5086; type: Gene Expression) and (ID: MSTRG.12; name: MSTRG.12; type: Gene Expression). All feature IDs must be distinct.
```

While I realize this is somewhat strange data, it does seem there is an assuption being made that all `gene_id` records share the same `gene_name`, but this is not explicitly checked during `mkref` or later, resulting in a somewhat confusing error.

**Comment by pratarora** [comment]
Hi @lparsons,
How did you solve this? I am facing the same error...

**Comment by csawye01** [comment]
Hi @lparsons I am also experiencing this error and am not sure a way around it.

**Comment by A-N-Other** [comment]
This remains an issue - are there any updates here? Preparing a reference from a GTF downloaded directly from Ensembl (should be fairly 'best practice', therefore) works without issue, but `cellranger count` then fails with the above error.
