### ISSUE TITLE
Issue with mkref

### ISSUE THREAD

**Issue by sbhattacharya3** [10XGenomics/cellranger#5]
Hi,

I am trying to build the reference genome for drosophila by using cellranger mkref command. Please find below the commands used.
[sbhattach2@CRI-13-127 cellranger-2.1.0]$ sudo ./cellranger mkgtf /data/Suro/Drosophila_melanogaster.BDGP6.91.gtf /data/Suro/Drosophila_melanogaster.BDGP6.91_filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_biotype:lincRNA --attribute=gene_biotype:antisense

[sbhattach2@CRI-13-127 cellranger-2.1.0]$ sudo ./cellranger mkref --genome=dros6 --fasta=../Drosophila_melanogaster.BDGP6.cds.all.fa.gz --genes=/data/Suro/Drosophila_melanogaster.BDGP6.91_filtered.gtf
/home/sbhattach2/cellranger-2.1.0/cellranger-cs/2.1.0/bin
cellranger mkref (2.1.0)
Copyright (c) 2017 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------

Creating new reference folder at /home/sbhattach2/cellranger-2.1.0/dros6
...done

Writing genome FASTA file into reference folder...
...done

Computing hash of genome FASTA file...
...done

Writing genes GTF file into reference folder...
**WARNING: The following transcripts appear on multiple chromosomes in the GTF:**

This can indicate a problem with the reference or annotations. Only the first chromosome will be counted.
...done

Computing hash of genes GTF file...
...done

Writing genes index file into reference folder (may take over 10 minutes for a 3Gb genome)...
Traceback (most recent call last):
  File "/home/sbhattach2/cellranger-2.1.0/cellranger-cs/2.1.0/bin/mkref", line 100, in <module>
    main()
  File "/home/sbhattach2/cellranger-2.1.0/cellranger-cs/2.1.0/bin/mkref", line 97, in main
    referenceBuilder.build_reference()
  File "/home/sbhattach2/cellranger-2.1.0/cellranger-cs/2.1.0/lib/python/cellranger/reference.py", line 213, in build_reference
    self.write_genome_gene_index(new_gene_index, new_gene_gtf, new_genome_fasta)
  File "/home/sbhattach2/cellranger-2.1.0/cellranger-cs/2.1.0/lib/python/cellranger/reference.py", line 311, in write_genome_gene_index
    gene_index = GeneIndex(in_gtf_fn, in_fasta_fn)
  File "/home/sbhattach2/cellranger-2.1.0/cellranger-cs/2.1.0/lib/python/cellranger/reference.py", line 386, in __init__
    fasta_parser = FastaParser(self.in_fasta_fn)
  File "/home/sbhattach2/cellranger-2.1.0/cellranger-cs/2.1.0/lib/python/cellranger/reference.py", line 316, in __init__
    self.chroms = self.load_fasta(in_fasta_fn)
  File "/home/sbhattach2/cellranger-2.1.0/cellranger-cs/2.1.0/lib/python/cellranger/reference.py", line 336, in load_fasta
    current_seq.append(line)
**AttributeError: 'NoneType' object has no attribute 'append'**

I have put the error and the warning in bold. Can you please suggest me a workaround?

Thanks,
Surajit

**Comment by pryvkin10x** [comment]
Hi, you appear to be using a transcript FASTA file - mkref requires a genome sequence.

**Comment by sbhattacharya3** [comment]
Thanks it worked.
