### ISSUE TITLE
Unexpected failure at chunk_reads

### ISSUE THREAD

**Issue by jrknoedler** [10XGenomics/cellranger#75]
I'm getting this error message at chunk_reads. Some details: I'm running in cluster mode on a slurm server, and the pipeline has worked with no issues as recently as a few months ago but is now failing on both new and old (i.e. previously working) fastq files. The only differences is I'm using a reference gtf with one entry manually removed, but it seems to be failing before that could possibly have been an issue.

Traceback (most recent call last):
  File "/scratch/users/knoedler/cellranger-3.1/martian-cs/v3.2.3/adapters/python/martian_shell.py", line 589, in _main
    stage.main()
  File "/scratch/users/knoedler/cellranger-3.1/martian-cs/v3.2.3/adapters/python/martian_shell.py", line 554, in main
    self._run(lambda: self._module.main(args, outs))
  File "/scratch/users/knoedler/cellranger-3.1/martian-cs/v3.2.3/adapters/python/martian_shell.py", line 523, in _run
    cmd()
  File "/scratch/users/knoedler/cellranger-3.1/martian-cs/v3.2.3/adapters/python/martian_shell.py", line 554, in <lambda>
    self._run(lambda: self._module.main(args, outs))
  File "/scratch/users/knoedler/cellranger-3.1/cellranger-cs/3.1/mro/stages/common/chunk_reads/__init__.py", line 53, in main
    tk_subproc.check_call(chunk_reads_args)
  File "/scratch/users/knoedler/cellranger-3.1/cellranger-cs/3.1/tenkit/lib/python/tenkit/log_subprocess.py", line 37, in check_call
    return subprocess.check_call(*args, **kwargs)
  File "/scratch/users/knoedler/cellranger-3.1/miniconda-cr-cs/4.3.21-miniconda-cr-cs-c10/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['chunk_reads', '--reads-per-fastq', '5000000', '/scratch/users/knoedler/IntactMalePOA_Kiss1gtftest2/SC_RNA_COUNTER_CS/SC_RNA_COUNTER/_BASIC_SC_RNA_COUNTER/CHUNK_READS/fork0/chnk0-u16d99aa408/files/', 'fastq_chunk', '--martian-args', 'chunk_args.json', '--compress', 'lz4']' returned non-zero exit status -9

**Comment by evolvedmicrobe** [comment]
Hi @jrknoedler,

Please reach out to support@10xgenomics.com for quick help with his issue.  An exit status of `-9` means that something sent a `SIGKILL` to the process, and this may indicate an issue with the cluster configuration, or some other problem, that they'll be able to help you with.

Cheers,
Nigel
