### ISSUE TITLE
troobleshooting creating custom reference with cellranger-atac 

### ISSUE THREAD

**Issue by El-Castor** [10XGenomics/cellranger#91]
Hi, 

I'm trying to create a custom reference folder to used cellRanger-atac on my single celle ATAC-seq data with this command : 

```bash
cellranger-atac mkref $folderRefName --config $configFilePath
```

using this config file as show in you example: 

```bash
{
    GENOME_FASTA_INPUT: "/K/FLOCAD/DATA/OMICS/Melon/DNAseq/AdnaneB/Genome_PacBio/toulouse_assemblage/CMiso1.1/20180606/CMiso1.1_genome.fa.gz",
    GENE_ANNOTATION_INPUT: "/K/FLOCAD/DATA/OMICS/Melon/DNAseq/AdnaneB/Genome_PacBio/toulouse_assemblage/CMiso1.1/20180606/annotation/v2.0/CMiso1.1_GM2.0_gene_model.gtf",
    MOTIF_INPUT: "http://jaspar.genereg.net/download/CORE/JASPAR2020_CORE_plants_non-redundant_pfms_jaspar.txt",
    ORGANISM: "Cucumis melo",
    PRIMARY_CONTIGS: ["CMiso1.1chr01", "CMiso1.1chr02", "CMiso1.1chr03", "CMiso1.1chr04", "CMiso1.1chr05", "CMiso1.1chr06", "CMiso1.1chr07", "CMiso1.1chr08", "CMiso1.1chr09", "CMiso1.1chr10", "CMiso1.1chr11", "CMiso1.1chr12"],
    NON_NUCLEAR_CONTIGS: ["CMiso1.1chr00"]
}
```

so I launch this command but I get an error as you can see in this log :

```bash
bcl2fastq_bihCubi_2.20.0.422) cpichot@node15:/NetScratch/cpichot/singleCell_ATACseq$ cellranger-atac mkref $folderRefName --config $configFilePath
cellranger-atac mkref (1.2.0)
Copyright (c) 2019 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/NetScratch/cpichot/soft/cellranger-atac-1.2.0/cellranger-atac-1.2.0/cellranger-atac-cs/1.2.0/bin/mkref", line 6, in <module>
    from reference import ReferenceBuilder, STANDARD_GENOMES
  File "/NetScratch/cpichot/soft/cellranger-atac-1.2.0/cellranger-atac-1.2.0/cellranger-atac-cs/1.2.0/lib/python/reference.py", line 30, in <module>
    import utils
  File "/NetScratch/cpichot/soft/cellranger-atac-1.2.0/cellranger-atac-1.2.0/cellranger-atac-cs/1.2.0/lib/python/utils.py", line 21, in <module>
    from sklearn.utils import sparsefuncs
  File "/NetScratch/cpichot/soft/cellranger-atac-1.2.0/cellranger-atac-1.2.0/miniconda-atac-cs/4.3.21-miniconda-atac-cs-c10/lib/python2.7/site-packages/sklearn/__init__.py", line 134, in <module>
    from .base import clone
  File "/NetScratch/cpichot/soft/cellranger-atac-1.2.0/cellranger-atac-1.2.0/miniconda-atac-cs/4.3.21-miniconda-atac-cs-c10/lib/python2.7/site-packages/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/NetScratch/cpichot/soft/cellranger-atac-1.2.0/cellranger-atac-1.2.0/miniconda-atac-cs/4.3.21-miniconda-atac-cs-c10/lib/python2.7/site-packages/sklearn/utils/__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "/NetScratch/cpichot/soft/cellranger-atac-1.2.0/cellranger-atac-1.2.0/miniconda-atac-cs/4.3.21-miniconda-atac-cs-c10/lib/python2.7/site-packages/sklearn/utils/validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "/NetScratch/cpichot/soft/cellranger-atac-1.2.0/cellranger-atac-1.2.0/miniconda-atac-cs/4.3.21-miniconda-atac-cs-c10/lib/python2.7/site-packages/sklearn/utils/fixes.py", line 144, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "/NetScratch/cpichot/soft/cellranger-atac-1.2.0/cellranger-atac-1.2.0/miniconda-atac-cs/4.3.21-miniconda-atac-cs-c10/lib/python2.7/site-packages/scipy/sparse/linalg/__init__.py", line 117, in <module>
    from .eigen import *
  File "/NetScratch/cpichot/soft/cellranger-atac-1.2.0/cellranger-atac-1.2.0/miniconda-atac-cs/4.3.21-miniconda-atac-cs-c10/lib/python2.7/site-packages/scipy/sparse/linalg/eigen/__init__.py", line 11, in <module>
    from .arpack import *
  File "/NetScratch/cpichot/soft/cellranger-atac-1.2.0/cellranger-atac-1.2.0/miniconda-atac-cs/4.3.21-miniconda-atac-cs-c10/lib/python2.7/site-packages/scipy/sparse/linalg/eigen/arpack/__init__.py", line 22, in <module>
    from .arpack import *
  File "/NetScratch/cpichot/soft/cellranger-atac-1.2.0/cellranger-atac-1.2.0/miniconda-atac-cs/4.3.21-miniconda-atac-cs-c10/lib/python2.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 45, in <module>
    from . import _arpack
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory
```

I don't get any idea what I do wrong during the install of the software. Do you have any suggestion please ?

Thanks in advance

**Comment by El-Castor** [comment]
up ?

**Comment by evolvedmicrobe** [comment]
Hi @El-Castor please contact support@10xgenomics.com for help with this issue.
